### ISSUE TITLE
DataError: invalid input syntax for integer: "one2many_v_id_541"

### ISSUE THREAD

**Issue by wmena** [vertelab/odoo-project_scrum#3]
Hello Dude,

I'm having this error when I create a task inside of a Story and then select To-Do.

Full error below:

Traceback (most recent call last):
  File "/srv/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/odoo/addons/project_scrum/project_scrum.py", line 208, in write
    return super(project_task, self).write(vals)
  File "/srv/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/srv/odoo/addons/project/project.py", line 1039, in write
    write_vals = vals_reset_kstate if t.stage_id.id != new_stage else vals
  File "/srv/odoo/openerp/fields.py", line 817, in __get__
    self.determine_value(record)
  File "/srv/odoo/openerp/fields.py", line 910, in determine_value
    record._prefetch_field(self)
  File "/srv/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/models.py", line 3229, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/srv/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/srv/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/models.py", line 3297, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/srv/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/srv/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "one2many_v_id_541"
LINE 2: ...                      WHERE "project_task".id IN ('one2many_...
                                                             ^

**Comment by anderswallenquist** [comment]
Thank you for reporting this.

We will check this out.

Regards

Anders Wallenquist

Vertel AB


Den 2015-06-26 15:51, Willy Mena skrev:
