### ISSUE TITLE
ProgrammingError: relation "report_project_task_user" does not exist

### ISSUE THREAD

**Issue by oerp-odoo** [vertelab/odoo-project_scrum#6]
Error is thrown (when project_scrum is installed), when going to reporting/project/tasks analysis/: 
```python
Traceback (most recent call last):
  File "/home/oerp/openerp80/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/oerp/openerp80/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/oerp/openerp80/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/oerp/openerp80/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/oerp/openerp80/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/oerp/openerp80/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/oerp/openerp80/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/models.py", line 2142, in read_group
    cr.execute(query, where_clause_params)
  File "/home/oerp/openerp80/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "report_project_task_user" does not exist
LINE 3:             FROM "report_project_task_user" LEFT JOIN "proje...
```

If I uninstall project_scrum, error disappears. I don't know how but it messes this reporting view for project module.

**Comment by roman204** [comment]
+1 with project_scrm installed

**Comment by Tito1337** [comment]
Anybody figured this out? I have this bug with a custom module that inherits and extends tasks

**Comment by mlaitinen** [comment]
A workaround is to run the SQL query in `addons/project/report/project_report.py`. It's not a sustainable solution, because if you update `project` module, the SQL view gets removed.
